[project]
name = "aws-llm-usage"
version = "0.1.0"
description = "Show which Bedrock LLMs are used in your account, and their relative consumption."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.15",
    "tabulate>=0.9.0",
]
